(require 'package)

;;-------------------------------------------------------------
;; On-demand installation of packages
;;-------------------------------------------------------------
(defun require-package (package &optional min-version no-refresh)
  "Ask elpa to install given package."
  (if (package-installed-p package min-version)
      t
    (if (or (assoc package package-archive-contents) no-refresh)
	(package-install package)
      (progn
	(package-refresh-contents)
	(require-package package min-version t)))))

;;-------------------------------------------------------------
;; Set up repositories
;;-------------------------------------------------------------
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("tromey" . "http://tromey.com/elpa/"))
(add-to-list 'package-archives '("mepla" . "http://melpa.milkbox.net/packages/"))
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))

;;-------------------------------------------------------------
;; Install packages
;;-------------------------------------------------------------

(package-initialize)
(require-package 'ac-nrepl)
(require-package 'ac-slime)
(require-package 'ace-jump-mode)
(require-package 'auto-complete)
(require-package 'autopair)
(require-package 'clojure-mode)
(require-package 'clojure-test-mode)
(require-package 'clojurescript-mode)
(require-package 'coffee-mode)
(require-package 'color-theme-sanityinc-solarized)
(require-package 'color-theme-sanityinc-tomorrow)
(require-package 'crontab-mode)
(require-package 'csv-mode)
(require-package 'csv-nav)
(require-package 'darcsum)
(require-package 'diminish)
(require-package 'dired+)
(require-package 'dsvn)
(require-package 'durendal)
(require-package 'eldoc-eval)
(require-package 'elein)
(require-package 'elisp-slime-nav)
(require-package 'erlang)
(require-package 'exec-path-from-shell)
(require-package 'expand-region)
(require-package 'fill-column-indicator)
(require-package 'flymake-coffee)
(require-package 'flymake-css)
(require-package 'flymake-cursor)
(require-package 'flymake-haml)
(require-package 'flymake-jslint)
(require-package 'flymake-php)
(require-package 'flymake-python-pyflakes)
(require-package 'flymake-ruby)
(require-package 'flymake-sass)
(require-package 'flymake-shell)
(require-package 'gist)
(require-package 'git-blame)
(require-package 'gnuplot)
(require-package 'haml-mode)
(require-package 'haskell-mode)
(require-package 'hippie-expand-slime)
(require-package 'hl-sexp)
(require-package 'htmlize)
(require-package 'ibuffer-vc)
(require-package 'ido-ubiquitous)
(require-package 'inf-ruby)
(require-package 'js-comint)
(require-package 'js2-mode)
(require-package 'js3-mode)
(require-package 'json)
(require-package 'less-css-mode)
(require-package 'lively)
(require-package 'lua-mode)
(require-package 'magit)
(require-package 'markdown-mode)
(require-package 'marmalade)
(require-package 'maxframe)
(require-package 'mic-paren)
(require-package 'mmm-mode)
(require-package 'move-text)
(require-package 'multiple-cursors)
(require-package 'mwe-log-commands)
(require-package 'nrepl)
(require-package 'org-fstree)
(require-package 'page-break-lines)
(require-package 'paredit)
(require-package 'php-mode)
(require-package 'pointback)
(require-package 'pretty-mode)
(require-package 'project-local-variables)
(require-package 'rainbow-delimiters)
(require-package 'rainbow-mode)
(require-package 'regex-tool)
(require-package 'rinari)
(require-package 'ruby-compilation)
(require-package 'ruby-mode)
(require-package 'sass-mode)
(require-package 'scratch)
(require-package 'session)
(require-package 'slime)
(require-package 'slime-fuzzy)
(require-package 'slime-repl)
(require-package 'smarty-mode)
(require-package 'smex)
(require-package 'textile-mode)
(require-package 'tidy)
(require-package 'todochiku)
(require-package 'unfill)
(require-package 'vc-darcs)
(require-package 'wgrep)
(require-package 'whole-line-or-region)
(require-package 'yaml-mode)
(require-package 'yari)

(provide 'init-elpa)
